version: '2'
services:
  postgres-benchmarks:
    ports:
      - 5432:5432/tcp
    expose:
      - 5432
    image: pgbench-tools 
    volumes:
      - /var/lib/postgresql/data
    labels:
      io.rancher.container.start_once: true