version: '2'
services:
  postgres:
    image: postgres:9.5.3
    ports:
      - 5432:5432/tcp
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  postgres-benchmarks:
    image: pgbench-tools 
    ports:
      - 5432:5432/tcp
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - TESTHOST=postgres
      - RESULTHOST=127.0.0.1
    labels:
      io.rancher.container.start_once: true